//! Headless validation: WGSL shaders must parse and validate with naga
//! (the same compiler wgpu uses at runtime), and scene parsing must work.

use coldworking_viewer::scene;

fn validate_wgsl(name: &str, src: &str) {
    let module = naga::front::wgsl::parse_str(src)
        .unwrap_or_else(|e| panic!("{name}: WGSL parse error:\n{}", e.emit_to_string(src)));
    let mut validator = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::default(),
    );
    validator
        .validate(&module)
        .unwrap_or_else(|e| panic!("{name}: WGSL validation error: {e:?}"));
}

#[test]
fn trace_shader_valid() {
    validate_wgsl("trace.wgsl", include_str!("../src/shaders/trace.wgsl"));
}

#[test]
fn blit_shader_valid() {
    validate_wgsl("blit.wgsl", include_str!("../src/shaders/blit.wgsl"));
}

const TINY_SCENE: &str = r#"{
  "format": "coldworking-render-scene",
  "version": 1,
  "projectName": "test",
  "units": "in",
  "materials": [
    {"name": "air", "cauchyA": 1.0, "cauchyB": 0.0, "tint": [0,0,0]},
    {"name": "bk7", "cauchyA": 1.5046, "cauchyB": 0.0042, "tint": [0.004,0.004,0.006]}
  ],
  "coatings": [{"name": "c", "bins": [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,
    0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,0.5,0.5]}],
  "triangles": {
    "positions": [0,0,0, 1,0,0, 0,1,0,  0,0,1, 1,0,1, 0,1,1],
    "normals": [0,0,-1, 0,0,-1],
    "matFront": [0, 0],
    "matBack": [1, 1],
    "coating": [-1, 0]
  },
  "bbox": {"min": [0,0,0], "max": [1,1,1]}
}"#;

#[test]
fn parse_scene() {
    let s = scene::parse(TINY_SCENE).expect("parse");
    assert_eq!(s.tri_count, 2);
    assert_eq!(s.tris.len(), 8); // 4 vec4 per tri
    assert_eq!(s.materials.len(), 4); // 2 vec4 per material
    assert_eq!(s.coatings.len(), 32);
    assert_eq!(s.name, "test");
    // BVH-reordered triangle data must carry the right per-side materials.
    for t in 0..2 {
        assert_eq!(s.tris[t * 4][3], 0.0, "front = air");
        assert_eq!(s.tris[t * 4 + 1][3], 1.0, "back = glass");
    }
    // One triangle is coated, one is not — order may differ after BVH build.
    let coats: Vec<f32> = (0..2).map(|t| s.tris[t * 4 + 2][3]).collect();
    assert!(coats.contains(&-1.0) && coats.contains(&0.0));
}

#[test]
fn reject_wrong_format() {
    let r = scene::parse(r#"{"format": "something-else", "materials": [], "coatings": [],
        "triangles": {"positions": [], "normals": [], "matFront": [], "matBack": [], "coating": []},
        "bbox": {"min": [0,0,0], "max": [1,1,1]}}"#);
    assert!(r.is_err());
}

#[test]
fn reject_truncated_json() {
    assert!(scene::parse("{\"format\": \"coldworking-render-sc").is_err());
}

/// The demo scene exported by the web tooling must load, if present
/// (generated by `node tools/export_demo_scene.mjs`).
#[test]
fn load_exported_demo_if_present() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../demo.render.json");
    if path.exists() {
        let s = scene::load(&path).expect("demo scene loads");
        assert!(s.tri_count > 100, "demo should have many triangles");
        assert!(s.materials.len() >= 2 * 2);
    }
}
